/**
 * Centralized error IDs for tracking and monitoring
 * Use these IDs with logError to track error patterns in production
 */
export const ErrorIds = {
  // Auth errors
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Database errors
  DB_READ_FAILED: 'DB_READ_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_DELETE_FAILED: 'DB_DELETE_FAILED',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',

  // Event errors
  EVENT_CREATE_FAILED: 'EVENT_CREATE_FAILED',
  EVENT_UPDATE_FAILED: 'EVENT_UPDATE_FAILED',
  EVENT_DELETE_FAILED: 'EVENT_DELETE_FAILED',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',

  // Task errors
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',
  TASK_UPDATE_FAILED: 'TASK_UPDATE_FAILED',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',

  // Notification errors
  NOTIFICATION_CREATE_FAILED: 'NOTIFICATION_CREATE_FAILED',
  NOTIFICATION_DELETE_FAILED: 'NOTIFICATION_DELETE_FAILED',
  NOTIFICATION_JOB_FAILED: 'NOTIFICATION_JOB_FAILED',
  NOTIFICATION_SCHEDULE_FAILED: 'NOTIFICATION_SCHEDULE_FAILED',
  DIGEST_SEND_FAILED: 'DIGEST_SEND_FAILED',
  DIGEST_QUERY_FAILED: 'DIGEST_QUERY_FAILED',

  // Recurrence errors
  RECURRENCE_CREATE_FAILED: 'RECURRENCE_CREATE_FAILED',
  RECURRENCE_DELETE_FAILED: 'RECURRENCE_DELETE_FAILED',
  RECURRENCE_EXPAND_FAILED: 'RECURRENCE_EXPAND_FAILED',

  // Calendar sync errors
  CALENDAR_SOURCE_CREATE_FAILED: 'CALENDAR_SOURCE_CREATE_FAILED',
  CALENDAR_SOURCE_UPDATE_FAILED: 'CALENDAR_SOURCE_UPDATE_FAILED',
  CALENDAR_SOURCE_DELETE_FAILED: 'CALENDAR_SOURCE_DELETE_FAILED',
  CALENDAR_SYNC_FETCH_FAILED: 'CALENDAR_SYNC_FETCH_FAILED',
  CALENDAR_SYNC_PARSE_FAILED: 'CALENDAR_SYNC_PARSE_FAILED',
  CALENDAR_SYNC_UPSERT_FAILED: 'CALENDAR_SYNC_UPSERT_FAILED',

  // Budget/Finance errors
  BUDGET_CREATE_FAILED: 'BUDGET_CREATE_FAILED',
  BUDGET_UPDATE_FAILED: 'BUDGET_UPDATE_FAILED',
  BUDGET_DELETE_FAILED: 'BUDGET_DELETE_FAILED',
  EXPENSE_CREATE_FAILED: 'EXPENSE_CREATE_FAILED',
  EXPENSE_UPDATE_FAILED: 'EXPENSE_UPDATE_FAILED',
  EXPENSE_DELETE_FAILED: 'EXPENSE_DELETE_FAILED',
  INCOME_CREATE_FAILED: 'INCOME_CREATE_FAILED',
  INCOME_UPDATE_FAILED: 'INCOME_UPDATE_FAILED',
  INCOME_DELETE_FAILED: 'INCOME_DELETE_FAILED',
  CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',
  ACCOUNT_CREATE_FAILED: 'ACCOUNT_CREATE_FAILED',
  ACCOUNT_UPDATE_FAILED: 'ACCOUNT_UPDATE_FAILED',
  ACCOUNT_DELETE_FAILED: 'ACCOUNT_DELETE_FAILED',
  FATURA_OPERATION_FAILED: 'FATURA_OPERATION_FAILED',

  // Import errors
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  IMPORT_VALIDATION_FAILED: 'IMPORT_VALIDATION_FAILED',
  IMPORT_SAVE_FAILED: 'IMPORT_SAVE_FAILED',

  // User settings errors
  SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED',
  SETTINGS_READ_FAILED: 'SETTINGS_READ_FAILED',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Generic errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export type ErrorId = typeof ErrorIds[keyof typeof ErrorIds];
